# Generated by Django 4.0.4 on 2022-04-17 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_model', models.TextField(blank=True, choices=[('Муж', 'Муж'), ('Жен', 'Жен')], default='Муж', null=True, verbose_name='пол')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата начала трудовой деятельности')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('job', models.TextField(blank=True, choices=[('Ректор', 'Ректор'), ('Преподаватель', 'Преподаватель')], default='Ректор', null=True, verbose_name='Должность')),
                ('work_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='место работы(фелиал)')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='введите номер в формате +7', max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
