# Generated by Django 4.0.4 on 2022-04-26 07:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2004, 4, 26, 0, 0))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2022, 4, 26, 12, 12, 29, 46861))], verbose_name='Дата начала трудовой деятельности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы(филиал)'),
        ),
    ]
