# Generated by Django 4.0.4 on 2022-04-17 21:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата Окончания')),
                ('educational_organization', models.CharField(max_length=100, verbose_name='Образовательная организация')),
                ('name_theme', models.CharField(max_length=100, verbose_name='Наименование программы/темы')),
                ('number_document', models.PositiveSmallIntegerField(unique=True, verbose_name='№ документа')),
                ('duration_of_training', models.PositiveSmallIntegerField(verbose_name='Срок обучения(мес.)')),
                ('number_of_hours', models.PositiveSmallIntegerField(verbose_name='Колличество часов')),
                ('the_direction_of_self_development', models.TextField(choices=[('Учебно-организационное направление', 'Учебно-организационное направление'), ('Научно-методическое направление', 'Научно-методическое направление'), ('Организационно-воспитательное направление', 'Организационно-воспитательное направление')], default='Учебно-организационное направление', verbose_name='Направление саморазвития')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(choices=[('незаконченное высшее', 'незаконченное высшее'), ('среднее', 'среднее'), ('среднее профессиональное', 'среднее профессиональное'), ('среднее специальное', 'среднее специальное'), ('профессиональная переподготовка', 'профессиональная переподготовка'), ('высшее', (('специалитет', 'специалитет'), ('бакалавриат', 'бакалавриат'), ('магистратура', 'магистратура'), ('аспирантура', 'аспирантура'), ('кандидат наук', 'кандидат наук'), ('доктор наук', 'доктор наук')))], default='незаконченное высшее', verbose_name='Уровень')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факульет')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('educational_organization', models.CharField(max_length=100, verbose_name='Образовательная организация')),
                ('date', models.DateField(verbose_name='Дата Окончания')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements_type', models.CharField(choices=[('Свидетельство', 'Свидетельство'), ('Сертификат', 'Сертификат'), ('Благодарность', 'Благодарность'), ('Награда', 'Награда'), ('Ученая степень', 'Ученая степень'), ('Ученое звание', 'Ученое звание')], default='Ученое звание', max_length=14, verbose_name='Тип')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('date_of_receiving', models.DateField(help_text='Формат дд.мм.гггг', verbose_name='Дата получения')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'docx', 'doc', 'pdf'])], verbose_name='Фаил')),
                ('the_direction_of_self_development', models.TextField(choices=[('Учебно-организационное направление', 'Учебно-организационное направление'), ('Научно-методическое направление', 'Научно-методическое направление'), ('Организационно-воспитательное направление', 'Организационно-воспитательное направление')], default='Учебно-организационное направление', verbose_name='Направление саморазвития')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
