# Generated by Django 4.0.4 on 2022-04-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='number_of_hours',
            field=models.PositiveSmallIntegerField(verbose_name='Количество часов'),
        ),
    ]
