# Generated by Django 4.0.4 on 2022-04-26 07:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_professionaldevelopment_number_of_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date_of_receiving',
            field=models.DateField(help_text='Формат дд.мм.гггг', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 4, 26))], verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 4, 26))], verbose_name='Дата Окончания'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 4, 26))], verbose_name='Дата Окончания'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='duration_of_training',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Срок обучения(мес.)'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='number_of_hours',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=10)], verbose_name='Количество часов'),
        ),
    ]
