# Generated by Django 4.0.4 on 2022-05-05 05:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_achievements_date_of_receiving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date_of_receiving',
            field=models.DateField(help_text='Формат дд.мм.гггг', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 5, 5))], verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 5, 5))], verbose_name='Дата Окончания'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2022, 5, 5))], verbose_name='Дата Окончания'),
        ),
    ]
