# Generated by Django 4.0.4 on 2022-05-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievements_date_of_receiving_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Достижения', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='professionaldevelopment',
            options={'verbose_name': 'Повышение квалификации', 'verbose_name_plural': 'Повышение квалификации'},
        ),
    ]
