# Generated by Django 4.0.4 on 2022-04-17 21:45

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_start', models.SmallIntegerField(default='1900', verbose_name='от какого года ')),
                ('date_end', models.SmallIntegerField(default='2100', verbose_name='до какого года')),
                ('ray', models.SmallIntegerField(default='2', help_text='Внесите колличество достижений(точное число)', verbose_name='Репродуктивно-адаптивный уровень')),
                ('apy', models.SmallIntegerField(default='5', help_text='Внесите колличество достижений(точное число)', verbose_name='Активно-поисковый уровень ')),
                ('ity', models.SmallIntegerField(default='7', help_text='Внесите колличество достижений(точное число)', verbose_name='Интенсивно-творческий уровень  ')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
