# Generated by Django 4.0.4 on 2022-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='apy',
            field=models.SmallIntegerField(default='2', help_text='Внесите колличество достижений(точное число)', verbose_name='Активно-поисковый уровень '),
        ),
        migrations.AlterField(
            model_name='images',
            name='ity',
            field=models.SmallIntegerField(default='3', help_text='Внесите колличество достижений(точное число)', verbose_name='Интенсивно-творческий уровень  '),
        ),
        migrations.AlterField(
            model_name='images',
            name='ray',
            field=models.SmallIntegerField(default='1', help_text='Внесите колличество достижений(точное число)', verbose_name='Репродуктивно-адаптивный уровень'),
        ),
    ]
