# Generated by Django 4.0.4 on 2022-05-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='key',
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Редактирование планок уровня саморазвития преподавателя', 'verbose_name_plural': 'Редактирование планок уровня саморазвития преподавателя'},
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
